export const ACTIVITIES = [{"ID":1,"Title":"Primera tarea rey, matrices dispersas","Description":"Re easy pri, solo busquen en Google.","Type":"Calificable","CreationDate":"2021-01-08 12:00:00","LimitDate":"2021-01-10 12:00:00","CourseID":1,"ClinicalCaseID":3,"HCNID":1,"Difficulty":3},{"ID":2,"Title":"Actividad de prueba","Description":"Por favor ignoren esta actividad, gracias.","Type":"Prueba","CreationDate":"2021-01-09 11:43:21","LimitDate":"2021-01-19 10:59:59","CourseID":2,"ClinicalCaseID":2,"HCNID":2,"Difficulty":1}];
export const STUDENTS = [{"ID":1,"Name":"Daniel Gómez Sermeño","Email":"goma@email.com"},{"ID":2,"Name":"Xavier Garzón López","Email":"xavgar9@email.com"},{"ID":3,"Name":"Juan F. Gil","Email":"transfer10@email.com"},{"ID":4,"Name":"Edgar Silva","Email":"ednosil@email.com"},{"ID":5,"Name":"Juanita María Parra Villamíl","Email":"juanitamariap@email.com"},{"ID":6,"Name":"Sebastián Rodríguez Osorio Silva","Email":"sebasrosorio98@email.com"},{"ID":7,"Name":"Andrés Felipe Garcés","Email":"andylukast@email.com"}];
export const COURSES = [{"ID":1,"TeacherID":1,"Name":"Introducción a Matlab","CreationDate":"2021-01-01 12:00:00"},{"ID":2,"TeacherID":1,"Name":"Matlab avanzado","CreationDate":"2021-01-01 12:20:08"},{"ID":3,"TeacherID":2,"Name":"Clases de piano","CreationDate":"2021-01-06 15:21:50"},{"ID":4,"TeacherID":3,"Name":"Manejando en Cali","CreationDate":"2021-01-05 11:40:12"}];
export const ANNOUNCEMENTS = [{"ID":1,"CourseID":1,"Title":"¡Bienvenidos al curso!","Description":"Este es un curso básico de Matlab. LOS AMO.","CreationDate":"2021-01-19 03:33:48"},{"ID":2,"CourseID":1,"Title":"¡Primera tarea!","Description":"Resuelvan una matriz dispersa 100x100.","CreationDate":"2021-01-19 03:33:48"},{"ID":3,"CourseID":1,"Title":"Hola a todos","Description":"Hola muchachos, los quiero mucho. Estudien bye!","CreationDate":"2021-01-19 03:33:48"},{"ID":4,"CourseID":1,"Title":"Material guía","Description":"Busquen en Youtube. \"Accidentes de tránsito graves sin censura.\"","CreationDate":"2021-01-19 03:33:48"}];
export const FEEDBACKS = [{"ID":1,"ActivityID":1,"StudentID":1},{"ID":2,"ActivityID":1,"StudentID":2},{"ID":3,"ActivityID":1,"StudentID":3},{"ID":4,"ActivityID":1,"StudentID":4},{"ID":5,"ActivityID":1,"StudentID":5},{"ID":6,"ActivityID":1,"StudentID":6},{"ID":7,"ActivityID":1,"StudentID":7}];


export const CCASES = [{"ID":1,"Title":"El joven parchado","Description":"Benjamón era un joven con IMC PARCHADO.","Media":"../activitiesresources/img1.png","TeacherID":1},{"ID":2,"Title":"El pianista de la selva","Description":"Re La Mi Do#","Media":"../activitiesresources/img2.png","TeacherID":2},{"ID":3,"Title":"Muerte accidental","Description":"¿Por qué se fue? ¿Y por qué murió? ¿Por qué el Señor me la quitó? Se ha ido al cielo y para poder ir yo...","Media":"../activitiesresources/ElUltimoBeso.mp3","TeacherID":3}];
export const HCN = [{"ID":1,"TeacherID":1},{"ID":2,"TeacherID":1},{"ID":3,"TeacherID":1},{"ID":4,"TeacherID":2},{"ID":5,"TeacherID":3}];

export const USERS = [];

